### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by kendalsickels-wf** [xvrh/puppeteer-dart#108]
We've recently made the switch from Dart Webdriver to Puppeteer-dart as our primary testing solution and I was curious if I could get push access. Should any issues arise with a version of Chrome similar to the uploadFile issues from earlier in the year and you are unavailable for whatever reason (vacation, stepped away from the project, etc...), it would be nice to have a fallback option to push changes.

**Comment by xvrh** [comment]
Sure, I just invited you.
I agree that multiple collaborators to maintain this library is a good thing.
I don't have any plan for this library right now, the main puppeteer node library seems pretty quiet and I think we are on par with it. So feel free to evolve it as you want.
