### ISSUE TITLE
Invalid character in response header value

### ISSUE THREAD

**Issue by renatoathaydes** [xvrh/puppeteer-dart#113]
I am not certain this bug is coming from this lib, but I see the problem with the following class:

```
package:puppeteer/src/page/network_manager.dart
class Response
```

So maybe you can have a look... I have a server sending back a HTTP response looking like this:

```
HTTP/1.1 200 OK
Server: nginx/1.15.9
Date: Wed, 22 Apr 2020 15:40:48 GMT
Content-Type: image/svg+xml
Content-Length: 3284
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Wed, 22 Apr 2020 14:12:10 GMT
ETag: "5ea050ba-cd4"
Accept-Ranges: bytes
Expires: Wed, 29 Apr 2020 15:40:48 GMT
Cache-Control: max-age=604800
Pragma: public
Cache-Control: public

...
```

This is perfectly valid and curl and other http clients are fine with this response. But when I try to read the header values from Puppeteer's `Response` class and set its headers to a `dart:io` headers instance, it fails on the `cache-control` header:

```
Unhandled exception:
FormatException: Invalid HTTP header field value: "max-age=604800\npublic"
#0      _HttpHeaders._validateValue (dart:_http/http_headers.dart:604:9)
#1      _HttpHeaders._addAll (dart:_http/http_headers.dart:67:18)
#2      _HttpHeaders.add (dart:_http/http_headers.dart:57:5)
```

I found it strange that a new-line ended up in the middle of the header value, but the debugger shows the same thing:

<img width="443" alt="Screenshot 2020-04-22 at 17 50 17" src="https://user-images.githubusercontent.com/1901277/80003781-ca8cc880-84c1-11ea-85b3-151ae073b217.png">

This seems like a bug in the HTTP response parser?! Is this something I should report to some other library, or you think you can have a look into this?

**Comment by renatoathaydes** [comment]
I did a request like the browser does, acceping gzip (as you can see, the `content-encoding` is set to `gzip` in the image above), and the response changes slightly, but maybe this helps you debug what's wrong:

```
HTTP/1.1 200 OK
Server: nginx/1.15.9
Date: Wed, 22 Apr 2020 15:57:46 GMT
Content-Type: image/svg+xml
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Wed, 22 Apr 2020 14:12:10 GMT
ETag: W/"5ea050ba-cd4"
Expires: Wed, 29 Apr 2020 15:57:46 GMT
Cache-Control: max-age=604800
Pragma: public
Cache-Control: public
Content-Encoding: gzip

...
```

**Comment by xvrh** [comment]
Hi, thanks for the report.
I think that this is Chromium (and the Chrome DevTool) that concatenates the duplicated headers with a new line.

There is a similar question on the puppeteer repo: https://github.com/puppeteer/puppeteer/issues/5244
The resolution was to work around it on the app side. Maybe, you can just replace the `\n` with a comma?

If you really want to access the raw headers you can do it with the `data` property of the `Reponse` class. It points to the Chrome Devtools raw response and it has a `headersText`.
https://github.com/xvrh/puppeteer-dart/blob/master/lib/protocol/network.dart#L2004

**Comment by renatoathaydes** [comment]
@xvrh thanks for looking into it... I did use a similar workaround as you suggested, but that's pretty hacky. Using a new-line in a header value is very surprising as you get a header value that contains a forbidden character according to the HTTP spec (maybe that's why they used that, so it's safer to split values easily - still a very arbritary decision).
As I think this lib has nothing to do with the debate, I will close the issue.

Thanks again for the quick answer and for providing such a useful Dart library.
