### ISSUE TITLE
TargetClosedException(method: Runtime.callFunctionOn, reason: Connection.dispose(reason: Websocket.done(code: 1002, reason: null)))

### ISSUE THREAD

**Issue by SwissCheese5** [xvrh/puppeteer-dart#114]
Hi, I'm trying to scrape youtube as a learning experience to getting used to puppeteer.

I've tried many many variations of this code but it always throws this error

`TargetClosedException(method: Runtime.callFunctionOn, reason: Connection.dispose(reason: Websocket.done(code: 1002, reason: null)))` for every element in the array of dismissables

![chrome_2020-05-18_23-00-40](https://user-images.githubusercontent.com/7407478/82254505-9d65f580-995b-11ea-9e53-1c9156341d65.png)

```dart
    var browser = await puppeteer.launch();

    var page = await browser.newPage();

    await page.goto('https://www.youtube.com/results?search_query=${query.replaceAll(' ', '+')}', wait: Until.networkIdle);

    var videos = await page.$$('#dismissable');

    await Future.delayed(Duration(seconds: 10));
    var scrn = await page.screenshot(fullPage: true);
    await File('downloads/screen.png').writeAsBytes(scrn);
    videos.forEach((dismissable) async {
      try {
        var thumbnail = await dismissable.$('#thumbnail');
        var link = await dismissable
            .evaluateHandle(r'''( thumbnail, href ) => thumbnail.getAttribute( href );''', args: [thumbnail, 'href']);
        var jsonValue = await link.jsonValue;
        if (jsonValue == null || !jsonValue.startsWith('/watch?v=')) return;;
        print(jsonValue);
      } catch (e) {
        print(e);
      }
    });

    await browser.close();
```
`link` always returns a null value and throws the error.
![image](https://user-images.githubusercontent.com/7407478/82254159-07ca6600-995b-11ea-970c-de1d45f66381.png)
![image](https://user-images.githubusercontent.com/7407478/82254277-39433180-995b-11ea-88b9-78885c3f0623.png)

I've also tried dismissable.evaluate() with just `(element) => element.getAttribute('href')` and `args:[thumbnail]` And some other variations. I'm not sure what's going wrong..

The above code is an almost identical copy from the tests generated by puppetry https://puppetry.app/ because had given up and thought maybe I'm doing something wrong. But all the tests on the app pass flawlessly.
![image](https://user-images.githubusercontent.com/7407478/82254076-dce01200-995a-11ea-8a83-75b4ac9240d0.png)
![image](https://user-images.githubusercontent.com/7407478/82254118-f41eff80-995a-11ea-9351-9b14b21b1594.png)

**Comment by xvrh** [comment]
Hi,
You can try the `propertyValue` method on `ElementHandle`
Something like that seems to work for me:
```dart
import 'package:puppeteer/puppeteer.dart';

void main() async {
  var browser = await puppeteer.launch(headless: false);
  var page = await browser.newPage();

  await page.goto('https://www.youtube.com/results?search_query=puppeteer',
      wait: Until.networkIdle);

  var videos = await page.$$('#dismissable');

  for (var dismissable in videos) {
    var thumbnail = await dismissable.$('#thumbnail');
    var link = await thumbnail.propertyValue('href') as String;
    print(link);
  }

  await browser.close();
}
```

**Comment by SwissCheese5** [comment]
Oddly enough, the forEach was the problem... The for loop works...

Is this a dart feature? What's going on?

**Comment by xvrh** [comment]
With forEach, you are not "awaiting" the execution of the loop. So the browser is closed immediately.

**Comment by SwissCheese5** [comment]
Oh, that makes sense I suppose... Thank you
