### ISSUE TITLE
FileSystemException: Creation failed, path = '.local-chromium' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by SamratSahoo** [xvrh/puppeteer-dart#116]
Hi,

I was running the following function:
```
Future<void> login(String username, String password) async {

  // Launch Chrome Binaries
  var browser = await puppeteer.launch();

  // Open New Tab and go to HAC
  var page = await browser.newPage();
  await page.goto('https://hac.friscoisd.org/HomeAccess/Account/LogOn?ReturnUrl=%2fHomeAccess%2fClasses%2fClasswork', wait: Until.networkIdle);

  // Find Login IDs and Login
  await page.focus('#LogOnDetails_UserName');
  await page.keyboard.type(username);
  await page.focus('#LogOnDetails_Password');
  await page.keyboard.type(password);
  print(page);

}
```

when I received the following error:

> E/flutter (22593): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Creation failed, path = '.local-chromium' (OS Error: Read-only file system, errno = 30)

Any and all help is appreciated. Thank You

**Comment by SamratSahoo** [comment]
Looks like Puppeteer is only usable for desktop as per issue #74

**Comment by xvrh** [comment]
Indeed, you can't run a Chromium process directly on a mobile OS (this is a restriction of Android and iOS).
Your other option is to run the Chromium process on a server and access it remotely from a mobile client. This is achievable with the `puppeteer.connect` method.

**Comment by SamratSahoo** [comment]
Ah okay. Do you know where I could get more info on how to run the Chromium process via a server?

**Comment by talhakhan1297** [comment]
If puppeteer is only usable for desktop than why it say it supports Android / iOS on pub. 
![image](https://user-images.githubusercontent.com/50271102/100069505-aaa7f380-2e5a-11eb-8209-c3b73a977637.png)

**Comment by micDropper** [comment]
@talhakhan1297 Agreed. It ought to be clearly stated in the documentation the limits on Android and iOS. Developers shouldn't have to code it up (like me) or research issues to discover that a feature is not present when the documentation seems to indicate otherwise.

**Comment by abnerh69** [comment]
Please, re-open it.  I am using Puppeteer on MacOS (flutter desktop) and it works perfectly only when running from debugger.  But, when I try to run myApp.app directly from Finder, appears this same ERROR message.

Any help?

**Comment by xvrh** [comment]
@abnerh69 I think in your case you need to control the location where the chromium binary will be downloaded.

Something like that.
```dart
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:puppeteer/puppeteer.dart';

void main() async {
  var chromium = await downloadChrome(
    // Use a path where you have write access
    cachePath: path.join(Platform.environment['HOME']!, 'chromium-puppeteer'),
  );
  var browser = await puppeteer.launch(executablePath: chromium.executablePath);

  await browser.close();
}
```

**Comment by abnerh69** [comment]
Works!  Thank you @xvrh
