### ISSUE TITLE
On bundled chromium, can't play video mp4

### ISSUE THREAD

**Issue by drophouse01** [xvrh/puppeteer-dart#166]
The video is not playing on chromium. It works on chrome though. Seems it is missing video codex or something. Is there a way to enable them?

**Comment by xvrh** [comment]
You can look at this question from the puppeteer FAQ: https://github.com/puppeteer/puppeteer#q-what-features-does-puppeteer-not-support

> Puppeteer is bundled with Chromium — not Chrome — and so by default, it inherits all of Chromium's media-related limitations. This means that Puppeteer does not support licensed formats such as AAC or H.264. (However, it is possible to force Puppeteer to use a separately-installed version Chrome instead of Chromium via the executablePath option to puppeteer.launch. You should only use this configuration if you need an official release of Chrome that supports these media formats.)

**Comment by drophouse01** [comment]
No prob. For now, I have changed the format to WebM.
