### ISSUE TITLE
bad request 400 on some site

### ISSUE THREAD

**Issue by ysyfff** [xvrh/puppeteer-dart#179]
```dart
loadSite()async{
// String url = 'https://blog-ysy.vercel.app/';
    String url = 'http://cdjg.chengdu.gov.cn';
    var browser = await puppeteer.launch(headless: false);

    var page = await browser.newPage();

    await page.goto(url, wait: Until.load);

    var screenshot = await page.screenshot();

    await File('_github.png').writeAsBytes(screenshot);
    print('download finish');
}
```

Run the upper code and goto the network tab in devtools，you will see that the request response is 400，but the request response  is 200 on a normal browser。This is wired, I think there is something wrong in puppeteer。By the way, I tried puppeteer with node，and also get the response of bad request.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2571290/172024502-3b1917cb-9a8e-434b-ba43-48f683ecd350.png">

**Comment by xvrh** [comment]
Some website forbid "automated browser/bots".

Maybe you can try with the **"Stealth"** plugin which tries to hide all information that can tell that the request originate from a bot.

```dart
import 'package:puppeteer/plugins/stealth.dart';
import 'package:puppeteer/puppeteer.dart';

void main() async {
  puppeteer.plugins.add(StealthPlugin());
  await loadSite();
}
```

**Comment by ysyfff** [comment]
> 

Thanks man, you are correct, stealth worked.
