### ISSUE TITLE
client app's http request's custom headers replaced - is this puppeteer related?

### ISSUE THREAD

**Issue by isoos** [xvrh/puppeteer-dart#184]
`pub.dev` has a complex client logic that adds custom `Authorization` headers to some of the requests that are going to the server. When running locally and accessing it from Chrome, it works great, however, the same steps from puppeteer + headless Chrome seem to fail, because it seems that the `Authorization` header (and any custom header) seems to be replaced by default headers.

I can see the custom headers in the `page.onRequest` stream when it is about to start the request, but they are gone at the time the request hits the server. Is this a puppeteer / sandbox / headless behavior which I accidentally switched on?

(A PR that uses it and fails https://github.com/dart-lang/pub-dev/pull/6064 )

**Comment by xvrh** [comment]
@isoos Do you have a small example to reproduce what you are trying?

Here is what I do, and it seems the shelf handler correctly get the `Authorization: abc' header.

```dart
import 'package:puppeteer/puppeteer.dart';
import 'package:shelf/shelf_io.dart' as shelf;
import 'package:shelf/shelf.dart' as shelf;

void main() async {
  var server = await shelf.serve((request) async {
    print(request.headers);
    return shelf.Response.ok('ok');
  }, 'localhost', 0);

  var browser = await puppeteer.launch();
  var page = await browser.newPage();

  await page.setExtraHTTPHeaders({'Authorization': 'abc'});

  await page.goto('http://localhost:${server.port}');

  await server.close();
  await browser.close();
}
```

**Comment by isoos** [comment]
> await page.setExtraHTTPHeaders({'Authorization': 'abc'});

The extra header is coming from the HTTP request running in the page context (it is using package:http to create a client and add extra headers to PUT/POST/DELETE requests). Adding it on the page object could be a workaround though.

I'll try to create a small(ish) example.

**Comment by xvrh** [comment]
I quickly tried with a simple `fetch` in a js script and I see the headers correctly.
I need to test with a compiled dart app...

```dart
import 'dart:io';

import 'package:puppeteer/puppeteer.dart';
import 'package:shelf/shelf_io.dart' as shelf;
import 'package:shelf/shelf.dart' as shelf;

void main() async {
  var server = await shelf.serve((request) async {
    print('Request [${request.url}]');
    print(request.headers);

    if (request.url.path == '') {
      return shelf.Response.ok('<script>${_script()}</script>',
          headers: {'content-type': 'text/html'});
    } else {
      return shelf.Response.ok('ok');
    }
  }, 'localhost', 0);

  var browser = await puppeteer.launch(headless: true);
  var page = await browser.newPage();

  await page.goto('http://localhost:${server.port}', wait: Until.networkIdle);

  await server.close();
  await browser.close();
}

String _script() => '''
fetch("/fetch", {
    method: 'POST',
    headers: {
      'Authorization': 'xxx',
      'some-header': 'efg'
    }
  }
);
''';
```

**Comment by isoos** [comment]
I think I've found the core of the issue: the request interception's continueRequest overrides the headers:

add this code, and the headers are gone:
```
  await page.setRequestInterception(true);
  page.onRequest.listen((rq) async {
    await rq.continueRequest();
  });
```

Use the `headers: rq.headers` parameter, and they are back:
```
  await page.setRequestInterception(true);
  page.onRequest.listen((rq) async {
    await rq.continueRequest(headers: rq.headers);
  });
```
So maybe the fix could be as small as `headers ??= {...rq.headers};` in network_manager.dart#403 ?

**Comment by xvrh** [comment]
I think you are totally right. I opened https://github.com/xvrh/puppeteer-dart/pull/186 to fix it

**Comment by isoos** [comment]
Thank you!
