### ISSUE TITLE
Trouble downloading a csv file changing the filename

### ISSUE THREAD

**Issue by jeff9315** [xvrh/puppeteer-dart#185]
I'm hoping someone can help me. I've just started trying puppeteer and I can't get it to download a file anywhere but in the normal downloads directory or with a specific filename. I've tried it with both headless true and false. It just goes into my downloads directory with the filename mcpa.search.csv. Here is my code. I thought the comments about the order of the statements very confusing. So, it's possible that I'm doing something in the wrong order. This is on Windows 11 using puppeteer: 2.12.0 and Flutter 3.3 and Dart 2.18.

import 'dart:io';
import 'package:puppeteer/puppeteer.dart';

```
void main() async {
  final website = 'https://www.pa.marion.fl.us/PropertySearch.aspx';
  final browser = await puppeteer.launch(headless: false);
  final page = await browser.newPage();
  await page.goto(website);
  final title = await page.evaluate('() => document.title');
  print('Doc title: $title');

  final delimitedDataButton =
      await page.$('#MCPAMaster_MCPAContent_rblSearchBy_12');

  await delimitedDataButton.click();
  final candlerParcelPrefix = await page.$('#MCPAMaster_MCPAContent_txtParm');
  await candlerParcelPrefix.type('3531-');
  var futureFileChooser = page.waitForFileChooser();
  final searchButton = await page.$('#MCPAMaster_MCPAContent_btnWine');
  await searchButton.click();
  var fileChooser = await futureFileChooser;
  await fileChooser.accept([File('temp.csv')]);

  await browser.close();
  
}
```

**Comment by xvrh** [comment]
I think `waitForFileChooser` is to choose a file for file *upload*.

For file download it seems there is a method `setDownloadBehavior` in the CDP protocol. This method is deprecated but you can still use it:

```dart
  await page.devTools.page.setDownloadBehavior('allow', downloadPath: '/Users/xavier/Documents');
  await searchButton.click();
```

I'm not exactly sure how to do it without this command. I'll have to search.

**Comment by jeff9315** [comment]
I tried using that setDowloadBerhavior and it didn't put the file anywhere. I found conflicting info on the web about whether it had to be an absolute directory that already exists or a relative directory in your project file. I tried both.  My project is in the L drive so I tried /temp and L:/temp and C:/temp. I also have an example directory within my project. I couldn't put it there either.

**Comment by xvrh** [comment]
It doesn't really answer your question but there is always the possibility to directly execute the http request:

```dart
import 'package:http/http.dart';

void main() async {
  var data = await readBytes(Uri.https('www.pa.marion.fl.us', 'PropertySearch.aspx', {
    'SearchBy': 'Delimited Data',
    'Parms': '3531-',
  }));
  await File('temp.csv').writeAsBytes(data);
}
```

It only works in simple case like this one.
For more complex cases, you can also do this with some more sophisticated behaviour with `page.onRequest` and `page.setRequestInterception(true)`

**Comment by jeff9315** [comment]
Well, that worked PERFECTLY. Thanks Xavier!
