### ISSUE TITLE
Error on flutter web. Platform._environment

### ISSUE THREAD

**Issue by hadessama1994** [xvrh/puppeteer-dart#190]
I'm using flutter web on Windows, but I'm getting this message: 'Platform._environment'.
Also, the **.local-chromium** folder is not being created after calling puppeteer on my code.

Any hints? :)

**Comment by hacker1024** [comment]
You want a web app to create a local directory on your device? 🤨 

Anyway, this issue also occurs when connecting to an existing Chrome instance, which should in theory be possible (ignoring CORS).

**Comment by Joseph-Nathan** [comment]
how can i solve this ,
