### ISSUE TITLE
Expose `Worker` type to clients 

### ISSUE THREAD

**Issue by elliette** [xvrh/puppeteer-dart#198]
The [`Worker`](https://github.com/xvrh/puppeteer-dart/blob/68d54b8700804d090f8e97fa0742e3dd0293304a/lib/src/page/worker.dart) type is currently not exposed to clients. ([Here are all the types in the `page` subdirectory that are being exposed.](https://github.com/xvrh/puppeteer-dart/blob/68d54b8700804d090f8e97fa0742e3dd0293304a/lib/puppeteer.dart#L9-L34))

Exposing the `Worker` type would help clients of `package:puppeteer` that rely on worker manipulation / evaluation.

**Comment by xvrh** [comment]
Thanks. That looks like an oversight. It will be fixed with #200

**Comment by elliette** [comment]
> Thanks. That looks like an oversight. It will be fixed with #200

Excellent, thank you for the quick fix!
