### ISSUE TITLE
Expose `setter` for `TargetInfo` type

### ISSUE THREAD

**Issue by elliette** [xvrh/puppeteer-dart#201]
See https://github.com/puppeteer/puppeteer/issues/9371 for context and more details. 

Ideally this is something that should be fixed by Puppeteer. Currently the only way to use Puppeteer to interact with a Chrome DevTools panel added by a Chrome Extension is to set the `TargetInfo's` type to be a page. I've opened up https://github.com/puppeteer/puppeteer/issues/9371 in Puppeteer itself to request official support for this use case.

In the meantime, would it be possible to expose a setter (alongside the type [`getter`](https://github.com/xvrh/puppeteer-dart/blob/649f4b35a94917431a4c06cee1ea8b72043ac0b8/lib/src/target.dart#L54-L67)) to allow clients to coerce the type of a `Target`?

**Comment by xvrh** [comment]
@elliette feel free to open a pull request with your idea. I don't see any problem with this if it enable new use cases.

**Comment by elliette** [comment]
> @elliette feel free to open a pull request with your idea. I don't see any problem with this if it enable new use cases.

Thanks! I opened https://github.com/xvrh/puppeteer-dart/pull/202
