### ISSUE TITLE
page.waitForSelector('#selector', timeout: Duration.zero) throws instantly instead of disabling timeout

### ISSUE THREAD

**Issue by Wizzel1** [xvrh/puppeteer-dart#210]
The documentation says: 

>  [timeout]: maximum time to wait for. Pass [Duration.zero] to disable timeout. The default value can be changed by using the [page.defaultTimeout] property.

but when I use 

```dart
await page.waitForSelector('#selector', timeout: Duration.zero);
```
I instantly get an error : 

```
TimeoutException (TimeoutException: waiting for selector "#selector" failed: timeout 0ms exceeded)
```

**Comment by xvrh** [comment]
Good catch. Opened #211 to fix it. And I found an other bug with a uninitialised variable.

Thanks.
