### ISSUE TITLE
Is puppeteer-dart support the CDPSession?

### ISSUE THREAD

**Issue by gzlock** [xvrh/puppeteer-dart#227]
https://pptr.dev/api/puppeteer.cdpsession

I need to listen to the websocket message on the webpage. 
I can use the following javascript code to do it
```javascript
// ...blablabla
const client = await page.target().createCDPSession();
await client.send('Network.enable')
client.on('Network.webSocketFrameReceived', (params) => {
 console.log(params)
})
```

[But I didn’t find the relevant code in puppeteer](https://github.com/xvrh/puppeteer-dart/search?q=CDPSession)

**Comment by xvrh** [comment]
It's called `Session` and it's defined here: https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/connection.dart#L217

You might be interested in the `devTools` property accessible on `Page`. It gives you access to either the low-level client or to a fully typed API of the devtools protocol:

```dart
import 'package:puppeteer/puppeteer.dart';

void main() async {
  var browser = await puppeteer.launch();
  var page = await browser.newPage();

  // Use the typed API
  await page.devTools.network.enable();
  page.devTools.network.onWebSocketFrameReceived.listen((e) {
    print(e.response.payloadData);
  });

  // Go low-level and send the raw string directly
  var client = page.devTools.client;
  await client.send('Network.enable');
  client.onEvent.where((e) => e.name == 'Network.webSocketFrameReceived').listen((event) { 
    var params = event.parameters;
    // Do your stuff
  });
}
```
