### ISSUE TITLE
Will it work well if there are multiple puppeteer instance running at the same time.

### ISSUE THREAD

**Issue by ninhngadev** [xvrh/puppeteer-dart#229]
I see the original code define `Puppeteer._();` so I can not create more than one instance of puppeteer.
I modified it a bit to be able to create multiple instances of it.
If I do so, what problems might I encounter?
![image](https://user-images.githubusercontent.com/122073248/227692989-b5f58963-26c6-4deb-bb6c-0c4313834b1e.png)

**Comment by xvrh** [comment]
I think it should be totally safe to remote the private constructor and allow to instantiate a `Puppeteer` object.

If I remember well, it was made private just for simplicity and point the users to the `puppeteer` singleton global variable.

**Comment by ninhngadev** [comment]
Thank you. I just want to make sure it's safe to create multiple instances of Puppeteer at the same time and not have any problems.
