### ISSUE TITLE
[request] add  page.waitForFocus(selector);

### ISSUE THREAD

**Issue by Joseph-Nathan** [xvrh/puppeteer-dart#231]
when i try to get element ,
in my case it may be in the middle of the page ,
i try to do this ,
```
await page.waitForSelector(selector );
await page.focus( selector );
await page.click(selector);
```
but i get this
```
Error Scrape: Node is either not visible or not an HTMLElement
```
because the selector was not visible ant this moment ,
i there any way to sure if element is focused at this moment ?

**Comment by Joseph-Nathan** [comment]
```
await page.waitForSelector(selector, visible: true);
```
it work to find the element in the page ,
but if you want to click it , the element must be in the view ,
and ``` await page.waitForSelector(selector, visible: true); ```
not scroll it to be visible in the view of the page . 

to reproduce it , try to click element ,that in the page ,
 but not visible in the view " it may in the end of the page"

**Comment by xvrh** [comment]
The `click` method should scroll the element into view.
Code: https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/page/js_handle.dart#L350
Documentation: https://github.com/xvrh/puppeteer-dart/blob/master/doc/api.md#pageclick

This code is also working for me:

```dart
import 'package:puppeteer/puppeteer.dart';
import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf/shelf_io.dart' as shelf;

void main() async {
  var server = await shelf.serve((request) async {
    if (request.url.path == '') {
      return shelf.Response.ok('''<body>
<div style="height: 10000px; background-color: red"></div>
<button>Button</button>
</body>''', headers: {'content-type': 'text/html'});
    } else {
      return shelf.Response.ok('');
    }
  }, 'localhost', 0);

  var browser = await puppeteer.launch(headless: false);
  var page = await browser.newPage();

  await page.goto('http://localhost:${server.port}', wait: Until.networkIdle);

  await page.click('button');

  await server.close();
  await browser.close();
}
```

Can you provide a small reproducible example so I can better understand?

**Comment by Joseph-Nathan** [comment]
thanks for your time ,
it work after change from ```Until.networkIdle``` to ```Until.load```
