### ISSUE TITLE
Connecting via websocket throws an error because of missing map entry

### ISSUE THREAD

**Issue by Wizzel1** [xvrh/puppeteer-dart#248]
I am trying to connect to a brightdata scrapingbrowser but because the object I am recieving does not contain the "params" entry, an exception gets thrown.

![Unbenannt](https://github.com/xvrh/puppeteer-dart/assets/43343510/6f9e934d-8ea4-49dc-8f13-dbc92b613fb5)

**Comment by xvrh** [comment]
Something as simple as: `(object['params'] ?? {}) as Map<String, dynamic>` could unblock you?

I prefer you submit the pull request yourself once you have validated that it really works for you.

**Comment by Wizzel1** [comment]
I guess that should fix it. I wasn't sure if that could have any sideeffects so I wanted to hear your opinion first.

**Comment by xvrh** [comment]
I don't think it could break anything. It's just a bit suspicious and probably means that there is other subtle differences like that.

**Comment by Wizzel1** [comment]
I tried what you suggested but now I am getting another error : 
```type '_Map<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast ``` in the same line. Any idea why?

**Comment by xvrh** [comment]
My fault! The line should have been:

```dart
      _eventController.add(Event._(object['method'] as String,
          (object['params']) as Map<String, dynamic>? ?? {}));
```

**Comment by Wizzel1** [comment]
Yes that seems to work thanks. Looks like I already created a PR :D
