### ISSUE TITLE
Backport recent fixes to v2

### ISSUE THREAD

**Issue by lukeanderson-wk** [xvrh/puppeteer-dart#317]
Hello, there were a couple recent fixes that went in (https://github.com/xvrh/puppeteer-dart/pull/308 and https://github.com/xvrh/puppeteer-dart/pull/312).

But we are not on Dart 3 yet. Can these same fixes also be released on puppeteer-dart v2?

Thank you!

**Comment by xvrh** [comment]
Hi,
I published v2.25 on top of v2.24 with the 2 fixes.

Caution: no test (manual or automated) were run before the release process. This was just 2 git cherry picks.

Let me know if it helps.

**Comment by lukeanderson-wk** [comment]
Thanks, appreciate it!
