### ISSUE TITLE
too slow compared to puppeteer-sharp !!!

### ISSUE THREAD

**Issue by mr-savari** [xvrh/puppeteer-dart#59]
### great work 
i have been using **puppeteer-sharp** and it's generate pdf at rate of **70ms** in ready page mode but this one take about **700ms** !!!

**Comment by xvrh** [comment]
Hi

> great work

Thanks for your interest

> i have been using puppeteer-sharp and it's generate pdf at rate of 70ms in ready page mode but this one take about 700ms !!!

Can you provide a code snippet in C# and in Dart on how you measured the generation time? Thanks

I did a quick comparison with the Node.JS version and can't see any difference.
The bulk of the work is done by the Chromium process. The puppeteer role is just to send a json command and receive the result. If there is a big difference between Node, C# or Dart it should be easy to fix.

**Comment by xvrh** [comment]
After investigating, I could not witness any significant speed difference between Node.js, .NET and Dart.

I will close this issue. Feel free to reopen it with a concrete example.

**Comment by mrsavari** [comment]
> Hi
> 
> > great work
> 
> Thanks for your interest
> 
> > i have been using puppeteer-sharp and it's generate pdf at rate of 70ms in ready page mode but this one take about 700ms !!!
> 
> Can you provide a code snippet in C# and in Dart on how you measured the generation time? Thanks
> 
> I did a quick comparison with the Node.JS version and can't see any difference.
> The bulk of the work is done by the Chromium process. The puppeteer role is just to send a json command and receive the result. If there is a big difference between Node, C# or Dart it should be easy to fix.

sorry my machine was the issue. great work :)
