### ISSUE TITLE
Puppeteer Stealth Plugin

### ISSUE THREAD

**Issue by keimao** [xvrh/puppeteer-dart#60]
Would it be possible to add this plugin for Puppeteer? It will decrease detection on websites that do flag headless browsers.
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth

**Comment by xvrh** [comment]
Thanks for the idea. 
It seems useful and easy to do.

**Comment by xvrh** [comment]
Fixed with #62
An example of the StealthPlugin is here: https://github.com/xvrh/puppeteer-dart/blob/master/example/stealth_plugin.dart

Feedback welcome.
