### ISSUE TITLE
Remove `Flutter` tag from Pub.Dev 

### ISSUE THREAD

**Issue by mannprerak2** [xvrh/puppeteer-dart#76]
The [package](https://pub.dev/packages/puppeteer) has a tag `Flutter`. Consider replacing it with Dart or removing it

**Comment by xvrh** [comment]
Yes this package does not work on a mobile device and thus the Flutter tag is not correct (except for Flutter on Desktop?).

The tags are automatically added by the pub.dev website and I'm not aware of any way to remove it.
I think this is the relevant issue: https://github.com/dart-lang/pub-dev/issues/858

**Comment by mannprerak2** [comment]
oh alright, guess this issue makes no sense then.
