### ISSUE TITLE
Error when in headless mode with flutter for desktop

### ISSUE THREAD

**Issue by Kleak** [xvrh/puppeteer-dart#86]
i got this error almost everytime in headless mode with flutter for desktop (on linux didn't try other platform yet)

```
ServerException (Cannot find context with specified id)
```

The code that trigger the error is :
```
hasNextPage = html.querySelector('.pagination .next a') != null;
if (hasNextPage) {
  await page.clickAndWaitForNavigation('.pagination .next a');
}
```

The error is not raised when headless mode is false.
It's probably due to Flutter for Desktop but not sure

**Comment by Kleak** [comment]
it occurs also in non headless mode but i don't know why also the error is impossible to catch which is pretty annoying :/

**Comment by xvrh** [comment]
Hello Kevin,
Can you provide a full program with the problem?
I would like to fix this but I can't reproduce it.

Thanks

**Comment by Kleak** [comment]
it seems it was because i had a dialog above the element i want to click
