### ISSUE TITLE
Program Getting Stuck at puppeteer.launch()

### ISSUE THREAD

**Issue by siddharthborderwala** [xvrh/puppeteer-dart#88]
The code is as given:
var browser = await puppeteer.launch();

When the code is executed, it gets stuck there.

**Comment by xvrh** [comment]
Hello,
Thanks for the report.

- What OS are you using? (puppeteer only works on desktop, not on mobile platforms).
- The first time you execute `launch` it has to download a version a chromium in a folder named `.local-chromium` do you see it?
- Can you try to have more information with a debugger (ie. with Webstorm/Intellij or VisualStudio code). For instance, try to add a break-point and step-into the function to see where it stops.

Hopes that helps

**Comment by siddharthborderwala** [comment]
Hello,
Thanks for the response.
I am sorry, there I must have made a mistake before.
Now it works completely fine.

**Comment by siddharthborderwala** [comment]
Is there a way you can run this on mobile devices?

**Comment by xvrh** [comment]
Unfortunately this is not yet possible. You cannot launch Chrome on Android (or iOS) with the "devtools".

Puppeteer works this way: 
1. Start a Chrome process with some special flags to enable "automation" and headless.
When Chrome opens in this mode, it starts an http server and allows clients to connect to it.
2. The Puppeteer client (nodejs, dart...), opens a websocket connection and use the [Chrome DevTools protocol](https://chromedevtools.github.io/devtools-protocol/) to send the commands (navigate, click, etc...).

The second step can work on mobile (it's just opening a websocket and send json packets). The first step is not available on mobile OS's: You cannot start a local chrome process with some specific flags.
It is certainly possible to split the 2: have the chrome process running on a server (in docker for instance) and the clients automate it remotely from a Flutter app.
But I'm not sure if this is useful :-/

**Comment by siddharthborderwala** [comment]
Can you tell me how to communicate with the chrome browser with dart code?

**Comment by xvrh** [comment]
You can connect to an existing chrome instance with `puppeteer.connect` (https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/puppeteer.dart#L202)

You can connect from a mobile device to an instance running on a desktop.

**Comment by siddharthborderwala** [comment]
Thank you for the help!

**Comment by josedaniel-cb** [comment]
> The code is as given:
> var browser = await puppeteer.launch();
> 
> When the code is executed, it gets stuck there.

I solved it by activating devtools
`pub global activate devtools`

https://github.com/flutter/devtools/issues/773
