### ISSUE TITLE
Failure to launch Chrome/chromium in non-headless mode

### ISSUE THREAD

**Issue by kendalsickels-wf** [xvrh/puppeteer-dart#95]
Trying to run Chrome in non-headless mode within a linux docker container so I can record with Xvfb. Everything with Xvfb appears to be running but when `puppeteer.launch()` fires I get the following stack:

```
Exception: Websocket url not found
package:puppeteer/src/puppeteer.dart 312:3                      _waitForWebSocketUrl
===== asynchronous gap ===========================
dart:async                                                      _AsyncAwaitCompleter.completeError
package:puppeteer/src/puppeteer.dart                            _waitForWebSocketUrl
===== asynchronous gap ===========================
dart:async                                                      _asyncThenWrapperHelper
package:puppeteer/src/puppeteer.dart                            _waitForWebSocketUrl
package:puppeteer/src/puppeteer.dart 171:30                     Puppeteer.launch
===== asynchronous gap ===========================
dart:async                                                      _asyncThenWrapperHelper
package:puppeteer/src/puppeteer.dart                            Puppeteer.launch
```
Here is my launch command:
```
var browser = await puppeteer.launch(
      headless: false,
      noSandboxFlag: true,
      args: [
        '--disable-gpu',
        '--disable-setuid-sandbox',
        '--window-size=1920x1080',
        '--enable-automation',
        '--disable-dev-shm-usage',
      ]);
```
Headless mode works fine and non-headless works locally but not in the docker container. Any thoughts on this? Because this works locally on my mac I'm guessing there is either some dep I'm missing in my docker container or somehow puppeteer isn't seeing the running Xvfb display.

**Comment by xvrh** [comment]
Hello,
There is a test with headful mode that run in Travis-CI (container mode) (https://github.com/xvrh/puppeteer-dart/blob/master/test/headful_test.dart). 
It uses the default `dart` support for Travis that start a xvfb process (https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb). 

Here is a few ideas to debug your case:
- Enable the logs to see if the process exits with a message:
```dart
import 'package:logging/logging.dart';
import 'package:puppeteer/puppeteer.dart';

main() async {
  Logger.root
    ..level = Level.ALL
    ..onRecord.listen(print);

  var browser = await puppeteer.launch(headless: true);
}
```
- Fork this project and try to add a few prints/logs statements near the launch of the process.
https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/puppeteer.dart#L155
- Post your Dockerfile here so we can have a look and see if we think of something missing :-)

**Comment by kendalsickels-wf** [comment]
This was 100% an Xvfb setup issue and unrelated to puppteer-dart
